name: Run Python Script Daily

on:
  schedule:
    - cron: '58 16 * * *'
  workflow_dispatch:

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.1'

      - name: Install dependencies
        run: |
          pip install -r Backend/djangoBackend/requirements.txt

      - name: Run script
        run: |
          python Backend/djangoBackend/stockBuyer/alpaca_trading.py
